### ISSUE TITLE
milvus on ipv6 only

### ISSUE THREAD

**Issue by rajeevpadinharepattu** [milvus-io/milvus-helm#382]
Milvus version : 2.4.21
Kuberentes version : 1.22.12

I am trying to setup milvus-db on an ipv6 only cluster. but the milvus standalone pod is not getting up, and giving the below error.

NAME                                     READY   STATUS             RESTARTS          AGE
pod/milvus-etcd-0                        1/1     Running            0                 3d4h
pod/milvus-minio-7c65b8cd8c-js8cl        1/1     Running            0                 3d4h
pod/milvus-standalone-579cc9d946-kmpbz   0/1     CrashLoopBackOff   903 (3m41s ago)   3d4h

eic@devgpu01:~> kubectl logs -n milvus-db milvus-standalone-579cc9d946-kmpbz
2022/10/31 12:08:23 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
[2022/10/31 12:08:23.516 +00:00] [INFO] [paramtable/base_table.go:453] ["failed to parse pulsar config, assume pulsar not used"] [error="parse \"\": empty url"]
[2022/10/31 12:08:23.516 +00:00] [INFO] [logutil/logutil.go:165] ["Log directory"] [configDir=]
[2022/10/31 12:08:23.516 +00:00] [INFO] [logutil/logutil.go:166] ["Set log file to "] [path=]

    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Version:   v2.1.2
Built:     Fri Sep 16 06:40:43 UTC 2022
GitCommit: 3c3ba55c
GoVersion: go version go1.16.9 linux/amd64

open pid file: /run/milvus/standalone.pid
lock pid file: /run/milvus/standalone.pid
[2022/10/31 12:08:23.516 +00:00] [INFO] [roles/roles.go:358] ["starting running Milvus components"]
[2022/10/31 12:08:23.517 +00:00] [INFO] [paramtable/base_table.go:453] ["failed to parse pulsar config, assume pulsar not used"] [error="parse \"\": empty url"]
[2022/10/31 12:08:23.517 +00:00] [DEBUG] [paramtable/component_param.go:769] ["init cacheSize"] ["cacheSize (GB)"=0]
[2022/10/31 12:08:23.518 +00:00] [INFO] [paramtable/base_table.go:453] ["failed to parse pulsar config, assume pulsar not used"] [error="parse \"\": empty url"]
[2022/10/31 12:08:23.518 +00:00] [DEBUG] [server/global_rmq.go:55] ["initializing global rmq"] [path=/var/lib/milvus/rdb_data]
[2022/10/31 12:08:23.518 +00:00] [DEBUG] [server/rocksmq_impl.go:157] ["Start rocksmq "] ["max proc"=8] [parallism=1] ["lru cache"=4042490511]
[2022/10/31 12:08:23.593 +00:00] [INFO] [tso/tso.go:121] ["sync and save timestamp"] [last=2022/10/31 12:03:23.633 +00:00] [save=2022/10/31 12:08:26.593 +00:00] [next=2022/10/31 12:08:23.593 +00:00]
[2022/10/31 12:08:23.593 +00:00] [DEBUG] [server/rocksmq_retention.go:99] ["Rocksmq retention goroutine start!"]
[2022/10/31 12:08:23.594 +00:00] [INFO] [paramtable/base_table.go:453] ["failed to parse pulsar config, assume pulsar not used"] [error="parse \"\": empty url"]
[2022/10/31 12:08:23.595 +00:00] [DEBUG] [paramtable/component_param.go:769] ["init cacheSize"] ["cacheSize (GB)"=0]
[2022/10/31 12:08:23.595 +00:00] [INFO] [paramtable/base_table.go:453] ["failed to parse pulsar config, assume pulsar not used"] [error="parse \"\": empty url"]
[2022/10/31 12:08:23.595 +00:00] [INFO] [paramtable/base_table.go:453] ["failed to parse pulsar config, assume pulsar not used"] [error="parse \"\": empty url"]
panic: runtime error: index out of range [0] with length 0

goroutine 163 [running]:
github.com/go-basic/ipv4.LocalIP(...)
        /go/pkg/mod/github.com/go-basic/ipv4@v1.0.0/ip.go:26
github.com/milvus-io/milvus/internal/util/paramtable.(*grpcConfig).LoadFromEnv(...)
        /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:85
github.com/milvus-io/milvus/internal/util/paramtable.(*grpcConfig).init(0x5a99e40, 0x400b731, 0x9)
        /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:77 +0xd7
github.com/milvus-io/milvus/internal/util/paramtable.(*GrpcServerConfig).init(0x5a99e40, 0x400b731, 0x9)
        /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:130 +0x45
github.com/milvus-io/milvus/internal/util/paramtable.(*GrpcServerConfig).InitOnce.func1()
        /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:125 +0x3c
sync.(*Once).doSlow(0x5a9a100, 0xc000de5d18)
        /usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/util/paramtable.(*GrpcServerConfig).InitOnce(0x5a99e40, 0x400b731, 0x9)
        /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:124 +0x87
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init(0xc000c1e160, 0x8bdf3e, 0xc000360978)
        /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:154 +0x57
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run(0xc000c1e160, 0xc000c1e100, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:141 +0x2f
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run(0xc000dcf0c0, 0xffffffffffffffff, 0x43c4c28)
        /go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:55 +0x33
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord.func1(0x1, 0x43b2830, 0xc000be3300, 0xc0006681e8, 0xc000552890, 0xc000360970)
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:123 +0x125
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:106 +0xba

does milvus support ipv6 environments ?

**Comment by haorenfsa** [comment]
@rajeevpadinharepattu Hi, thanks for the feedback. We haven't carry out any test on ipv6 environments. And it's likely that developers didn't pay extra attention to it. So I'm not pretty sure it supports or not. 
Here's a couple of things we need to check, we're to claim that we supports ipv6 environment:

- [ ] 1. Whether the dependencies of milvus supports listening on ipv6 address:
  - [ ] etcd (required)
  - [ ] MinIO (optional, you can use AWS S3 or other S3 compatitable service)
  - [ ] kafka  or pulsar (optional, if you only uses milvus standalone mode, you can use built in rocksmq)
- [ ] 2. Whether the grpc server configration milvus uses supports ipv6 connections.
- [ ] 3. Whether the SDKs of milvus supports connection to an ipv6 address

So it's very like the answer will be NO as along as any conclusion listed above is a NO.

**Comment by haorenfsa** [comment]
According to the information you provided, it seems that the MinIO starts properly, while the etcd does not.
